[x,textdata] = xlsread('E:\recognition\country.xlsx');
countryname = textdata(2:173,1);
GDPperson=x(:,1)./x(:,5);
xlswrite('E:\recognition\GDPperson.xlsx',GDPperson);
X=[x(:,1:2),x(:,4),x(:,6)];
X = zscore(X); 

startdata = X([10,23,78,138],:);    % 选取第10、第23、第78和第138个观测为初始凝聚点
idx = kmeans(X,4,'Start',startdata);    % 设置初始凝聚点，进行K均值聚类
[S, H] = silhouette(X,idx);

countryname(idx == 1)
ans =

  15×1 cell 数组

    'Azerbaijan'
    'Barbados'
    'Bhutan'
    'Botswana'
    'Comoros'
    'Republic of Congo'
    'Equatorial Guinea'
    'Liberia'
    'Nigeria'
    'Saudi Arabia'
    'St. Kitts and Nevis'
    'Sudan'
    'Trinidad and Tobago'
    'Turkmenistan'
    'Venezuela'

countryname(idx == 2)
ans =

  100×1 cell 数组

    'Afghanistan'
    'Albania'
    'Algeria'
    'Angola'
    'Antigua and Barbuda'
    'Armenia'
    'The Bahamas'
    'Bahrain'
    'Bangladesh'
    'Belize'
    'Benin'
    'Bolivia'
    'Brazil'
    'Brunei Darussalam'
    'Burkina Faso'
    'Burundi'
    'Cabo Verde'
    'Cambodia'
    'Cameroon'
    'Central African Republic'
    'Chad'
    'Chile'
    'China'
    'Colombia'
    'Democratic Republic of the Congo'
    'Costa Rica'
    'Côte d'Ivoire'
    'Djibouti'
    'Dominican Republic'
    'Egypt'
    'El Salvador'
    'Eritrea'
    'Ethiopia'
    'Gabon'
    'The Gambia'
    'Georgia'
    'Ghana'
    'Grenada'
    'Guatemala'
    'Guinea'
    'Guinea-Bissau'
    'Guyana'
    'Haiti'
    'Honduras'
    'India'
    'Indonesia'
    'Islamic Republic of Iran'
    'Jamaica'
    'Jordan'
    'Kazakhstan'
    'Kenya'
    'Korea'
    'Kosovo'
    'Lao P.D.R.'
    'Lebanon'
    'FYR Macedonia'
    'Madagascar'
    'Malawi'
    'Malaysia'
    'Maldives'
    'Mali'
    'Mauritania'
    'Mauritius'
    'Mexico'
    'Morocco'
    'Mozambique'
    'Myanmar'
    'Namibia'
    'Nicaragua'
    'Niger'
    'Oman'
    'Pakistan'
    'Panama'
    'Papua New Guinea'
    'Paraguay'
    'Peru'
    'Philippines'
    'Romania'
    'Rwanda'
    'São Tomé and Príncipe'
    'Senegal'
    'Sierra Leone'
    'South Africa'
    'Sri Lanka'
    'St. Lucia'
    'St. Vincent and the Grenadines'
    'Suriname'
    'Swaziland'
    'Taiwan Province of China'
    'Tajikistan'
    'Tanzania'
    'Togo'
    'Tunisia'
    'Uganda'
    'Uruguay'
    'Uzbekistan'
    'Vietnam'
    'Yemen'
    'Zambia'
    'Zimbabwe'

countryname(idx == 3)
ans =

  33×1 cell 数组

    'Argentina'
    'Belarus'
    'Bosnia and Herzegovina'
    'Bulgaria'
    'Croatia'
    'Cyprus'
    'Czech Republic'
    'Dominica'
    'Ecuador'
    'Estonia'
    'Greece'
    'Hungary'
    'Italy'
    'Kuwait'
    'Kyrgyz Republic'
    'Latvia'
    'Lesotho'
    'Libya'
    'Malta'
    'Moldova'
    'Mongolia'
    'Montenegro'
    'Poland'
    'Portugal'
    'Russia'
    'Serbia'
    'Seychelles'
    'Slovak Republic'
    'Slovenia'
    'Solomon Islands'
    'Spain'
    'Turkey'
    'Ukraine'

countryname(idx == 4)
ans =

  24×1 cell 数组

    'Australia'
    'Austria'
    'Belgium'
    'Canada'
    'Denmark'
    'Finland'
    'France'
    'Germany'
    'Hong Kong SAR'
    'Iceland'
    'Ireland'
    'Israel'
    'Japan'
    'Luxembourg'
    'Netherlands'
    'New Zealand'
    'Norway'
    'Qatar'
    'Singapore'
    'Sweden'
    'Switzerland'
    'United Arab Emirates'
    'United Kingdom'
    'United States'
